# Generated by Django 5.1.2 on 2024-10-27 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Truck', 'Truck'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible')], max_length=20)),
                ('engine_type', models.CharField(choices=[('V6', 'V6'), ('V8', 'V8'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Diesel', 'Diesel')], max_length=20)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('mileage', models.PositiveIntegerField()),
                ('seating_capacity', models.PositiveIntegerField()),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Maintenance', 'Maintenance')], max_length=15)),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Needs Maintenance', 'Needs Maintenance')], max_length=20)),
                ('last_service_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('rental_start_date', models.DateField()),
                ('rental_end_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=15)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.car')),
            ],
        ),
    ]
